### PR TITLE
Created Navbar design

### PR DESCRIPTION
**Pull request by CoHarsh**
I have created a Navbar design and also try to make it responsive. 
if the window size is less than 900 px then other layout triggered but I couldn't do further.
I am pasting some photos of that navbar
image

### CODE REVIEW

**Comment by CoHarsh** [comment]
So sorry from My end I forgot to delete error generating commits 
commit id : 41e4cb5 is my final commit

**Comment by TheDeveloperD** [comment]
I have a suggestion @CoHarsh. Your previous design was more beautiful. Can you please revert back to it. And for responsiveness I don't thing we need such awesome effects as it would pop it like menu. So revert back to your previous design.

**Comment by CoHarsh** [comment]
I have tried a similar thing as before you mentioned @TheDeveloperD please take a look.
I overwrite the code for that CSS which I have shared an Image first.
Pull Request : 1a04163 output image:
Screenshot (531)

**Comment by TheDeveloperD** [comment]
Looks good to me. Merging your PR. Thank you for your contributions. 

And I appreciate your designing skills bro.

**Pull request merged**
