### PR TITLE
Added and styled service section

### PR DESCRIPTION
**Pull request by Ukesh-dev**
## Added Icons

### CODE REVIEW

**Comment by TheDeveloperD** [comment]
Thank you for your effort. But can you just update your local repo and just change the jsx as per file structure as it is creating conflicts. CSS looks good to me. Just the icons you added move that code to Services Section.

Also can you add a snap in your PR so that I can see the output.

**Comment by Ukesh-dev** [comment]
I guess the conflict is resolved now.
The output is 
Services

**Comment by TheDeveloperD** [comment]
Btw, have you already seen the tutorial for this portfolio cause the design looks ditto same. 

Jokes aside, Thank you for your contribution. I will merge your PR soon.

**Comment by Ukesh-dev** [comment]
Ok. Thanks. And would you mind giving it the label of HACTOBERFEST2021?

**Pull request merged**
