### PR TITLE
modifies css for about and skills section

### PR DESCRIPTION
**Pull request by SoundaryaKhanapur**
beautified about and skills section

### CODE REVIEW

**Comment by TheDeveloperD** [comment]
@SoundaryaKhanapur  Can you please attach a snap of the changes made by. So that I can just take a look the results of your work.

**Comment by SoundaryaKhanapur** [comment]
image
image
sure

**Comment by TheDeveloperD** [comment]
Actually I assigned you the main section. The first section which has text 'Hello, I am #ME'. I didnot assign you these sections. These were already assigned to someone else. Can you design the main section.

**Comment by SoundaryaKhanapur** [comment]
Okay, I got it wrong. Sure I'll work on the main section.

**Comment by SoundaryaKhanapur** [comment]
image
removed about and skill design and styled main section as assigned. I have created a separate pull request for this.

**Comment by TheDeveloperD** [comment]
As you have created a separate request for this and I have even merged it so I am closing this.

**Pull request closed without merging**
