### PR TITLE
main section updated with new style

### PR DESCRIPTION
**Pull request by CoHarsh**
I have updated the main section design and taken the image from outsource and I have given the link of that in the index.html
Here Is the final SS.
image
Here Logo word will contain Portfolio logo!

### CODE REVIEW

**Comment by TheDeveloperD** [comment]
Everything else looks good to me except logo. I will look into that. Thank you for your contribution. Merging your PR.

**Comment by priyansh71** [comment]
@TheDeveloperD  I think there is a typo in the main.js image import. It should be main-img.jpg
Screenshot 2021-10-04 at 15 18 58

**Comment by CoHarsh** [comment]
Can you confirm @TheDeveloperD @priyansh71 's comment

**Comment by TheDeveloperD** [comment]
I have updated main.js file. There was a typo but I have corrected it.

**Comment by CoHarsh** [comment]
main-img is another image and mainimg is another image

**Comment by TheDeveloperD** [comment]
Ok, so what's the difference and which one to keep

**Comment by CoHarsh** [comment]
I have done all the things in new PR which you have closed
main-img is old image and mainimg is the updated new image which I want to
put in the main section.
I have given source of mainimg.jpg in one of the closed PR which I made
before.

**Pull request merged**
