### PR TITLE
Main section Error Fixed

### PR DESCRIPTION
**Pull request by CoHarsh**

### CODE REVIEW

**Comment by TheDeveloperD** [comment]
I have already rectified the error. So I am closing this PR.

**Comment by CoHarsh** [comment]
there two are different images but if wish then no problem.

**Comment by TheDeveloperD** [comment]
@CoHarsh As per your comment I have opened this PR again. Do one thing keep both the images in the folder but the main.js. Then make the final commit which you think is the perfect one.

**Comment by CoHarsh** [comment]
Okay

**Pull request merged**
